"""Service boundary DTOs shared across domain service ports.

These immutable dataclasses define the canonical data exchanged between
application/domain orchestration and infrastructure adapters.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from datetime import datetime
    from pathlib import Path

    import numpy as np

    from cvcutter.shared.types import PrivacySetting


@dataclass(frozen=True)
class VideoProbeResult:
    """Technical metadata discovered from probing a media file."""

    duration_seconds: float
    resolution: tuple[int, int]
    codec: str
    frame_rate: float
    file_size_bytes: int
    has_audio: bool


@dataclass(frozen=True)
class VideoFrame:
    """A decoded video frame with timing/location metadata."""

    data: np.ndarray
    timestamp_seconds: float
    frame_index: int


@dataclass(frozen=True)
class AudioChunk:
    """A short window of audio samples used for analysis."""

    data: np.ndarray
    sample_rate: int
    start_seconds: float
    duration_seconds: float


@dataclass(frozen=True)
class PdfTextBlock:
    """A single ordered text block extracted from a PDF page."""

    text: str
    page_number: int
    block_index: int


@dataclass(frozen=True)
class AudioMixConfig:
    """Mixing parameters used when exporting a segment with external audio."""

    video_volume: float
    mic_volume: float
    mic_audio_path: Path | None
    sync_offset_seconds: float


@dataclass(frozen=True)
class Detection:
    """A single visual detection with class label, confidence, and bounding box."""

    class_name: str
    confidence: float
    bbox: tuple[float, float, float, float]


@dataclass(frozen=True)
class TranscriptionResult:
    """Complete speech transcription output for an audio source."""

    text: str
    segments: list[TranscriptionSegment]
    language: str
    confidence: float


@dataclass(frozen=True)
class TranscriptionSegment:
    """Timestamped section of text generated by speech transcription."""

    text: str
    start_seconds: float
    end_seconds: float
    confidence: float


@dataclass(frozen=True)
class ClassificationResult:
    """A scored audio-content label for a bounded time range."""

    label: str
    confidence: float
    start_seconds: float
    end_seconds: float


@dataclass(frozen=True)
class UploadMetadata:
    """Normalized metadata payload passed to upload adapters."""

    title: str
    description: str
    tags: list[str]
    privacy_status: PrivacySetting
    category_id: str
    playlist_id: str | None


@dataclass(frozen=True)
class UploadResult:
    """Outcome details for upload attempts, including resumable state."""

    success: bool
    video_id: str | None
    resumable_uri: str | None
    bytes_uploaded: int
    failure_kind: str | None
    resume_allowed: bool
    restart_from_zero: bool
    session_invalidated_at_utc: datetime | None
    error_message: str | None


@dataclass(frozen=True)
class DiskSpaceInfo:
    """Disk-capacity snapshot at a specific filesystem location."""

    total_bytes: int
    free_bytes: int
    path: Path


@dataclass(frozen=True)
class SuggestedMapping:
    """AI-suggested link from a segment to metadata records."""

    segment_id: str
    program_entry_id: str | None
    form_response_id: str | None
    confidence: float
    reason: str


@dataclass(frozen=True)
class MusicLookupMatch:
    """A scored candidate match returned by the music dictionary lookup."""

    work_id: str
    title: str
    composer: str | None
    performers: list[str]
    score: float
    dictionary_revision: str


@dataclass(frozen=True)
class ProgressEvent:
    """Progress notification payload emitted by long-running workflows."""

    stage: str
    current: int
    total: int
    message: str

